### ISSUE TITLE
make code public

### ISSUE THREAD

**Issue by aremazeilles** [STEPbySTEPproj/Protocol_biomechanics#17]
The procedure I use to make the algorithm accessible from the eurobench server starts with making a fork of your repository, and place it into the [eurobench namespace](https://github.com/eurobench).

Then from there I create a release and upload the docker image to the Docker Hub.
I usually do it from public repository. I did not try for private repository.

Would it be acceptable for you to switch this repository to public?

**Comment by dborro** [comment]
Done.

**Comment by aremazeilles** [comment]
cool, thanks
