### ISSUE TITLE
Extend root Readme

### ISSUE THREAD

**Issue by aremazeilles** [STEPbySTEPproj/Protocol_biomechanics#18]
When entering the repository, the [root readme](https://github.com/STEPbySTEPproj/Protocol_biomechanics) is quite short in information.

I would suggest to add some minimal information like:

* what this repo is about (data collection and processing) for the biomechanical characterisation of the human locomotion during stair waking), following the Eurobench protocol associated to it.
* What we can find in the repository: what is in `adquisition` and what is in `pi_algo`. 
* Possibly name the Step by Step project, and the authors. Euobench is already named.

What do you think?

**Comment by dborro** [comment]
Done.
